spring:
  application:
    name: board-crud

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: false
    open-in-view: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret-key: ${JWT_SECRET_KEY:?JWT_SECRET_KEY missing}
    access-expiration: 2592000000
    refresh-expiration: 2592000000

  datasource:
    url: ${DB_URL:?DB_URL missing}
    username: ${DB_USERNAME:?DB_USERNAME missing}
    password: ${DB_PASSWORD:?DB_PASSWORD missing}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${REDIS_URL:?REDIS_URL missing}
      port: ${REDIS_PORT:?REDIS_PORT missing}

  auth:
    attempt-window: 30
    lock-duration: 30

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS:?EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD:?EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  config:
    activate:
      on-profile: default

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.jdbc: DEBUG

#server:
#  forward-headers-strategy: framework
#  tomcat:
#    remoteip:
#      remote-ip-header: x-forwarded-for
#      protocol-header: x-forwarded-proto
