spring:
  application:
    name: Board-CRUD

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex
    username: bootuser
    password: Bootuser123!@#

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  jwt:
    secret: "q34sdfjaowerlk`21k2re!@#$qfquakld23848234wfnwerhwer8wer8234hqhr/234we23r19wefwber23bfwvgwer9@#Rnf13 4aodg7q@#%9afug23@#$Wefiaerh2345@3"
    expiration:
      refresh: 18000000
      access: 1200000

  data:
    redis:
      host: localhost
      port: 6379
